import katex from "katex";

export const greekAndHebrewLetters = [
  { icon: "\\alpha", render: "\\alpha" },
  { icon: "\\beta", render: "\\beta" },
  { icon: "\\gamma", render: "\\gamma" },
  { icon: "\\delta", render: "\\delta" },
  { icon: "\\epsilon", render: "\\epsilon" },
  { icon: "\\varepsilon", render: "\\varepsilon" },
  { icon: "\\zeta", render: "\\zeta" },
  { icon: "\\eta", render: "\\eta" },
  { icon: "\\theta", render: "\\theta" },
  { icon: "\\vartheta", render: "\\vartheta" },
  { icon: "\\iota", render: "\\iota" },
  { icon: "\\kappa", render: "\\kappa" },
  { icon: "\\lambda", render: "\\lambda" },
  { icon: "\\mu", render: "\\mu" },
  { icon: "\\nu", render: "\\nu" },
  { icon: "\\xi", render: "\\xi" },
  { icon: "o", render: "o" },
  { icon: "\\pi", render: "\\pi" },
  { icon: "\\varpi", render: "\\varpi" },
  { icon: "\\rho", render: "\\rho" },
  { icon: "\\varrho", render: "\\varrho" },
  { icon: "\\sigma", render: "\\sigma" },
  { icon: "\\varsigma", render: "\\varsigma" },
  { icon: "\\tau", render: "\\tau" },
  { icon: "\\upsilon", render: "\\upsilon" },
  { icon: "\\phi", render: "\\phi" },
  { icon: "\\varphi", render: "\\varphi" },
  { icon: "\\chi", render: "\\chi" },
  { icon: "\\psi", render: "\\psi" },
  { icon: "\\omega", render: "\\omega" },
  { icon: "A", render: "A" },
  { icon: "B", render: "B" },
  { icon: "\\Gamma", render: "\\Gamma" },
  { icon: "\\varGamma", render: "\\varGamma" },
  { icon: "\\Delta", render: "\\Delta" },
  { icon: "\\varDelta", render: "\\varDelta" },
  { icon: "E", render: "E" },
  { icon: "Z", render: "Z" },
  { icon: "H", render: "H" },
  { icon: "\\Theta", render: "\\Theta" },
  { icon: "\\varTheta", render: "\\varTheta" },
  { icon: "I", render: "I" },
  { icon: "K", render: "K" },
  { icon: "\\Lambda", render: "\\Lambda" },
  { icon: "\\varLambda", render: "\\varLambda" },
  { icon: "M", render: "M" },
  { icon: "N", render: "N" },
  { icon: "\\Xi", render: "\\Xi" },
  { icon: "\\varXi", render: "\\varXi" },
  { icon: "O", render: "O" },
  { icon: "\\Pi", render: "\\Pi" },
  { icon: "\\varPi", render: "\\varPi" },
  { icon: "P", render: "P" },
  { icon: "\\Sigma", render: "\\Sigma" },
  { icon: "\\varSigma", render: "\\varSigma" },
  { icon: "T", render: "T" },
  { icon: "\\Upsilon", render: "\\Upsilon" },
  { icon: "\\varUpsilon", render: "\\varUpsilon" },
  { icon: "\\Phi", render: "\\Phi" },
  { icon: "\\varPhi", render: "\\varPhi" },
  { icon: "X", render: "X" },
  { icon: "\\Psi", render: "\\Psi" },
  { icon: "\\varPsi", render: "\\varPsi" },
  { icon: "\\Omega", render: "\\Omega" },
  { icon: "\\varOmega", render: "\\varOmega" },
  { icon: "\\aleph", render: "\\aleph" },
  { icon: "\\beth", render: "\\beth" },
  { icon: "\\daleth", render: "\\daleth" },
  { icon: "\\gimel", render: "\\gimel" },
];

export const delimiters = [
  { icon: "|", render: "|" },
  { icon: "\\vert", render: "\\vert" },
  { icon: "\\|", render: "\\|" },
  { icon: "\\Vert", render: "\\Vert" },
  { icon: "(", render: "(" },
  { icon: ")", render: ")" },
  { icon: "[", render: "[" },
  { icon: "]", render: "]" },
  { icon: "\\{", render: "\\{" },
  { icon: "\\}", render: "\\}" },
  { icon: "\\langle", render: "\\langle" },
  { icon: "\\rangle", render: "\\rangle" },
  { icon: "\\lfloor", render: "\\lfloor" },
  { icon: "\\rfloor", render: "\\rfloor" },
  { icon: "\\lceil", render: "\\lceil" },
  { icon: "\\rceil", render: "\\rceil" },
  { icon: "/", render: "/" },
  { icon: "\\backslash", render: "\\backslash" },
  { icon: "\\Uparrow", render: "\\Uparrow" },
  { icon: "\\uparrow", render: "\\uparrow" },
  { icon: "\\Downarrow", render: "\\Downarrow" },
  { icon: "\\downarrow", render: "\\downarrow" },
  { icon: "\\llcorner", render: "\\llcorner" },
  { icon: "\\lrcorner", render: "\\lrcorner" },
  { icon: "\\ulcorner", render: "\\ulcorner" },
  { icon: "\\urcorner", render: "\\urcorner" },
  { icon: "\\left(abc\\right)", render: "\\left(abc\\right)" },
  { icon: "\\left[abc\\right]", render: "\\left[abc\\right]" },
  { icon: "\\left\\{abc\\right\\}", render: "\\left\\{abc\\right\\}" },
  {
    icon: "\\left\\langle abc \\right\\rangle",
    render: "\\left\\langle abc \\right\\rangle",
  },
  {
    icon: "\\left\\lvert abc \\right\\rvert",
    render: "\\left\\lvert abc \\right\\rvert",
  },
  {
    icon: "\\left\\lVert abc \\right\\rVert",
    render: "\\left\\lVert abc \\right\\rVert",
  },
  {
    icon: "\\left\\lfloor abc \\right\\rfloor",
    render: "\\left\\lfloor abc \\right\\rfloor",
  },
  {
    icon: "\\left\\lceil abc \\right\\rceil",
    render: "\\left\\lceil abc \\right\\rceil",
  },
  {
    icon: "\\left\\lfloor abc \\right\\rceil",
    render: "\\left\\lfloor abc \\right\\rceil",
  },
];

export const mathsConstructs = [
  { icon: "\\frac{abc}{xyz}", render: "\\frac{abc}{xyz}" },
  { icon: "\\frac{d^n y}{d x^n}", render: "\\frac{d^n y}{d x^n}" },
  { icon: "\\int_{a}^{b}  \\,dx", render: "\\int_{a}^{b}  \\,dx" },
  { icon: "\\lim_{x \\to \\infty}", render: "\\lim_{x \\to \\infty}" },
  { icon: "\\sum_{n = 1}^{\\infty}", render: "\\sum_{n = 1}^{\\infty}" },
  { icon: "\\sqrt{abc}", render: "\\sqrt{abc}" },
  { icon: "\\sqrt[n]{abc}", render: "\\sqrt[n]{abc}" },
  { icon: "\\overline{abc}", render: "\\overline{abc}" },
  { icon: "\\underline{abc}", render: "\\underline{abc}" },
  { icon: "\\widehat{abc}", render: "\\widehat{abc}" },
  { icon: "\\widetilde{abc}", render: "\\widetilde{abc}" },
  { icon: "\\overrightarrow{abc}", render: "\\overrightarrow{abc}" },
  { icon: "\\overleftarrow{abc}", render: "\\overleftarrow{abc}" },
  { icon: "\\overbrace{abc}", render: "\\overbrace{abc}" },
  { icon: "\\underbrace{abc}", render: "\\underbrace{abc}" },
  { icon: "\\binom{n}{k}", render: "\\binom{n}{k}" },
];

export const variableSizedSymbols = [
  { icon: "\\sum", render: "\\sum" },
  { icon: "\\prod", render: "\\prod" },
  { icon: "\\coprod", render: "\\coprod" },
  { icon: "\\int", render: "\\int" },
  { icon: "\\oint", render: "\\oint" },
  { icon: "\\iint", render: "\\iint" },
  { icon: "\\biguplus", render: "\\biguplus" },
  { icon: "\\bigcap", render: "\\bigcap" },
  { icon: "\\bigcup", render: "\\bigcup" },
  { icon: "\\bigoplus", render: "\\bigoplus" },
  { icon: "\\bigotimes", render: "\\bigotimes" },
  { icon: "\\bigodot", render: "\\bigodot" },
  { icon: "\\bigvee", render: "\\bigvee" },
  { icon: "\\bigwedge", render: "\\bigwedge" },
  { icon: "\\bigsqcup", render: "\\bigsqcup" },
];

export const standardFunctions = [
  { icon: "\\arccos", render: "\\arccos" },
  { icon: "\\cos", render: "\\cos" },
  { icon: "\\csc", render: "\\csc" },
  { icon: "\\exp", render: "\\exp" },
  { icon: "\\ker", render: "\\ker" },
  { icon: "\\limsup", render: "\\limsup" },
  { icon: "\\min", render: "\\min" },
  { icon: "\\sinh", render: "\\sinh" },
  { icon: "\\arcsin", render: "\\arcsin" },
  { icon: "\\cosh", render: "\\cosh" },
  { icon: "\\deg", render: "\\deg" },
  { icon: "\\gcd", render: "\\gcd" },
  { icon: "\\lg", render: "\\lg" },
  { icon: "\\ln", render: "\\ln" },
  { icon: "\\Pr", render: "\\Pr" },
  { icon: "\\sup", render: "\\sup" },
  { icon: "\\arctan", render: "\\arctan" },
  { icon: "\\cot", render: "\\cot" },
  { icon: "\\det", render: "\\det" },
  { icon: "\\hom", render: "\\hom" },
  { icon: "\\lim", render: "\\lim" },
  { icon: "\\log", render: "\\log" },
  { icon: "\\sec", render: "\\sec" },
  { icon: "\\tan", render: "\\tan" },
  { icon: "\\arg", render: "\\arg" },
  { icon: "\\coth", render: "\\coth" },
  { icon: "\\dim", render: "\\dim" },
  { icon: "\\inf", render: "\\inf" },
  { icon: "\\liminf", render: "\\liminf" },
  { icon: "\\max", render: "\\max" },
  { icon: "\\sin", render: "\\sin" },
  { icon: "\\tanh", render: "\\tanh" },
];

export const operatorsAndRelations = [
  { icon: "\\ast", render: "\\ast" },
  { icon: "\\star", render: "\\star" },
  { icon: "\\cdot", render: "\\cdot" },
  { icon: "\\bullet", render: "\\bullet" },
  { icon: "\\circ", render: "\\circ" },
  { icon: "\\bigcirc", render: "\\bigcirc" },
  { icon: "\\diamond", render: "\\diamond" },
  { icon: "\\times", render: "\\times" },
  { icon: "\\div", render: "\\div" },
  { icon: "\\centerdot", render: "\\centerdot" },
  { icon: "\\circledast", render: "\\circledast" },
  { icon: "\\circledcirc", render: "\\circledcirc" },
  { icon: "\\circleddash", render: "\\circleddash" },
  { icon: "\\dotplus", render: "\\dotplus" },
  { icon: "\\divideontimes", render: "\\divideontimes" },
  { icon: "\\pm", render: "\\pm" },
  { icon: "\\mp", render: "\\mp" },
  { icon: "\\amalg", render: "\\amalg" },
  { icon: "\\odot", render: "\\odot" },
  { icon: "\\ominus", render: "\\ominus" },
  { icon: "\\oplus", render: "\\oplus" },
  { icon: "\\oslash", render: "\\oslash" },
  { icon: "\\otimes", render: "\\otimes" },
  { icon: "\\wr", render: "\\wr" },
  { icon: "\\Box", render: "\\Box" },
  { icon: "\\boxplus", render: "\\boxplus" },
  { icon: "\\boxminus", render: "\\boxminus" },
  { icon: "\\boxtimes", render: "\\boxtimes" },
  { icon: "\\boxdot", render: "\\boxdot" },
  { icon: "\\square", render: "\\square" },
  { icon: "\\cap", render: "\\cap" },
  { icon: "\\cup", render: "\\cup" },
  { icon: "\\uplus", render: "\\uplus" },
  { icon: "\\sqcap", render: "\\sqcap" },
  { icon: "\\sqcup", render: "\\sqcup" },
  { icon: "\\wedge", render: "\\wedge" },
  { icon: "\\vee", render: "\\vee" },
  { icon: "\\dagger", render: "\\dagger" },
  { icon: "\\ddagger", render: "\\ddagger" },
  { icon: "\\barwedge", render: "\\barwedge" },
  { icon: "\\veebar", render: "\\veebar" },
  { icon: "\\curlywedge", render: "\\curlywedge" },
  { icon: "\\curlyvee", render: "\\curlyvee" },
  { icon: "\\Cap", render: "\\Cap" },
  { icon: "\\Cup", render: "\\Cup" },
  { icon: "\\bot", render: "\\bot" },
  { icon: "\\top", render: "\\top" },
  { icon: "\\intercal", render: "\\intercal" },
  { icon: "\\doublebarwedge", render: "\\doublebarwedge" },
  { icon: "\\lhd", render: "\\lhd" },
  { icon: "\\rhd", render: "\\rhd" },
  { icon: "\\triangleleft", render: "\\triangleleft" },
  { icon: "\\triangleright", render: "\\triangleright" },
  { icon: "\\unlhd", render: "\\unlhd" },
  { icon: "\\unrhd", render: "\\unrhd" },
  { icon: "\\bigtriangledown", render: "\\bigtriangledown" },
  { icon: "\\bigtriangleup", render: "\\bigtriangleup" },
  { icon: "\\setminus", render: "\\setminus" },
  { icon: "\\rightthreetimes", render: "\\rightthreetimes" },
  { icon: "\\leftthreetimes", render: "\\leftthreetimes" },
  { icon: "\\equiv", render: "\\equiv" },
  { icon: "\\cong", render: "\\cong" },
  { icon: "\\neq", render: "\\neq" },
  { icon: "\\sim", render: "\\sim" },
  { icon: "\\simeq", render: "\\simeq" },
  { icon: "\\approx", render: "\\approx" },
  { icon: "\\asymp", render: "\\asymp" },
  { icon: "\\doteq", render: "\\doteq" },
  { icon: "\\propto", render: "\\propto" },
  { icon: "\\models", render: "\\models" },
  { icon: "\\leq", render: "\\leq" },
  { icon: "\\geq", render: "\\geq" },
  { icon: "\\prec", render: "\\prec" },
  { icon: "\\succ", render: "\\succ" },
  { icon: "\\preceq", render: "\\preceq" },
  { icon: "\\succeq", render: "\\succeq" },
  { icon: "\\ll", render: "\\ll" },
  { icon: "\\gg", render: "\\gg" },
  { icon: "\\subset", render: "\\subset" },
  { icon: "\\supset", render: "\\supset" },
  { icon: "\\subseteq", render: "\\subseteq" },
  { icon: "\\supseteq", render: "\\supseteq" },
  { icon: "\\sqsubset", render: "\\sqsubset" },
  { icon: "\\sqsupset", render: "\\sqsupset" },
  { icon: "\\sqsubseteq", render: "\\sqsubseteq" },
  { icon: "\\sqsupseteq", render: "\\sqsupseteq" },
  { icon: "\\dashv", render: "\\dashv" },
  { icon: "\\vdash", render: "\\vdash" },
  { icon: "\\perp", render: "\\perp" },
  { icon: "\\mid", render: "\\mid" },
  { icon: "\\parallel", render: "\\parallel" },
  { icon: "\\bowtie", render: "\\bowtie" },
  { icon: "\\Join", render: "\\Join" },
  { icon: "\\ltimes", render: "\\ltimes" },
  { icon: "\\rtimes", render: "\\rtimes" },
  { icon: "\\smile", render: "\\smile" },
  { icon: "\\frown", render: "\\frown" },
  { icon: "\\in", render: "\\in" },
  { icon: "\\ni", render: "\\ni" },
  { icon: "\\notin", render: "\\notin" },
  { icon: "\\approxeq", render: "\\approxeq" },
  { icon: "\\thicksim", render: "\\thicksim" },
  { icon: "\\backsim", render: "\\backsim" },
  { icon: "\\backsimeq", render: "\\backsimeq" },
  { icon: "\\triangleq", render: "\\triangleq" },
  { icon: "\\circeq", render: "\\circeq" },
  { icon: "\\bumpeq", render: "\\bumpeq" },
  { icon: "\\Bumpeq", render: "\\Bumpeq" },
  { icon: "\\doteqdot", render: "\\doteqdot" },
  { icon: "\\thickapprox", render: "\\thickapprox" },
  { icon: "\\fallingdotseq", render: "\\fallingdotseq" },
  { icon: "\\risingdotseq", render: "\\risingdotseq" },
  { icon: "\\varpropto", render: "\\varpropto" },
  { icon: "\\therefore", render: "\\therefore" },
  { icon: "\\because", render: "\\because" },
  { icon: "\\eqcirc", render: "\\eqcirc" },
  { icon: "\\neq", render: "\\neq" },
  { icon: "\\leqq", render: "\\leqq" },
  { icon: "\\geqq", render: "\\geqq" },
  { icon: "\\leqslant", render: "\\leqslant" },
  { icon: "\\geqslant", render: "\\geqslant" },
  { icon: "\\lessapprox", render: "\\lessapprox" },
  { icon: "\\gtrapprox", render: "\\gtrapprox" },
  { icon: "\\lll", render: "\\lll" },
  { icon: "\\ggg", render: "\\ggg" },
  { icon: "\\lessdot", render: "\\lessdot" },
  { icon: "\\gtrdot", render: "\\gtrdot" },
  { icon: "\\lesssim", render: "\\lesssim" },
  { icon: "\\gtrsim", render: "\\gtrsim" },
  { icon: "\\eqslantless", render: "\\eqslantless" },
  { icon: "\\eqslantgtr", render: "\\eqslantgtr" },
  { icon: "\\precsim", render: "\\precsim" },
  { icon: "\\succsim", render: "\\succsim" },
  { icon: "\\precapprox", render: "\\precapprox" },
  { icon: "\\succapprox", render: "\\succapprox" },
  { icon: "\\Subset", render: "\\Subset" },
  { icon: "\\Supset", render: "\\Supset" },
  { icon: "\\subseteqq", render: "\\subseteqq" },
  { icon: "\\supseteqq", render: "\\supseteqq" },
  { icon: "\\preccurlyeq", render: "\\preccurlyeq" },
  { icon: "\\succcurlyeq", render: "\\succcurlyeq" },
  { icon: "\\curlyeqprec", render: "\\curlyeqprec" },
  { icon: "\\curlyeqsucc", render: "\\curlyeqsucc" },
  { icon: "\\blacktriangleleft", render: "\\blacktriangleleft" },
  { icon: "\\blacktriangleright", render: "\\blacktriangleright" },
  { icon: "\\trianglelefteq", render: "\\trianglelefteq" },
  { icon: "\\trianglerighteq", render: "\\trianglerighteq" },
  { icon: "\\vartriangleleft", render: "\\vartriangleleft" },
  { icon: "\\vartriangleright", render: "\\vartriangleright" },
  { icon: "\\lessgtr", render: "\\lessgtr" },
  { icon: "\\lesseqgtr", render: "\\lesseqgtr" },
  { icon: "\\lesseqqgtr", render: "\\lesseqqgtr" },
  { icon: "\\gtreqqless", render: "\\gtreqqless" },
  { icon: "\\gtreqless", render: "\\gtreqless" },
  { icon: "\\gtrless", render: "\\gtrless" },
  { icon: "\\backepsilon", render: "\\backepsilon" },
  { icon: "\\between", render: "\\between" },
  { icon: "\\pitchfork", render: "\\pitchfork" },
  { icon: "\\shortmid", render: "\\shortmid" },
  { icon: "\\smallfrown", render: "\\smallfrown" },
  { icon: "\\smallsmile", render: "\\smallsmile" },
  { icon: "\\Vdash", render: "\\Vdash" },
  { icon: "\\vDash", render: "\\vDash" },
  { icon: "\\Vvdash", render: "\\Vvdash" },
  { icon: "\\shortparallel", render: "\\shortparallel" },
  { icon: "\\nshortparallel", render: "\\nshortparallel" },
  { icon: "\\ncong", render: "\\ncong" },
  { icon: "\\nmid", render: "\\nmid" },
  { icon: "\\nparallel", render: "\\nparallel" },
  { icon: "\\nshortmid", render: "\\nshortmid" },
  { icon: "\\nshortparallel", render: "\\nshortparallel" },
  { icon: "\\nsim", render: "\\nsim" },
  { icon: "\\nVDash", render: "\\nVDash" },
  { icon: "\\nvDash", render: "\\nvDash" },
  { icon: "\\nvdash", render: "\\nvdash" },
  { icon: "\\ntriangleleft", render: "\\ntriangleleft" },
  { icon: "\\ntrianglelefteq", render: "\\ntrianglelefteq" },
  { icon: "\\ntriangleright", render: "\\ntriangleright" },
  { icon: "\\ntrianglerighteq", render: "\\ntrianglerighteq" },
  { icon: "\\nleq", render: "\\nleq" },
  { icon: "\\ngeq", render: "\\ngeq" },
  { icon: "\\nleqq", render: "\\nleqq" },
  { icon: "\\ngeqq", render: "\\ngeqq" },
  { icon: "\\nleqslant", render: "\\nleqslant" },
  { icon: "\\ngeqslant", render: "\\ngeqslant" },
  { icon: "\\nless", render: "\\nless" },
  { icon: "\\ngtr", render: "\\ngtr" },
  { icon: "\\nprec", render: "\\nprec" },
  { icon: "\\nsucc", render: "\\nsucc" },
  { icon: "\\npreceq", render: "\\npreceq" },
  { icon: "\\nsucceq", render: "\\nsucceq" },
  { icon: "\\precnapprox", render: "\\precnapprox" },
  { icon: "\\succnapprox", render: "\\succnapprox" },
  { icon: "\\precnsim", render: "\\precnsim" },
  { icon: "\\succnsim", render: "\\succnsim" },
  { icon: "\\lnapprox", render: "\\lnapprox" },
  { icon: "\\gnapprox", render: "\\gnapprox" },
  { icon: "\\lneq", render: "\\lneq" },
  { icon: "\\gneq", render: "\\gneq" },
  { icon: "\\lneqq", render: "\\lneqq" },
  { icon: "\\gneqq", render: "\\gneqq" },
  { icon: "\\lnsim", render: "\\lnsim" },
  { icon: "\\gnsim", render: "\\gnsim" },
  { icon: "\\lvertneqq", render: "\\lvertneqq" },
  { icon: "\\gvertneqq", render: "\\gvertneqq" },
  { icon: "\\nsubseteq", render: "\\nsubseteq" },
  { icon: "\\nsupseteq", render: "\\nsupseteq" },
  { icon: "\\nsubseteqq", render: "\\nsubseteqq" },
  { icon: "\\nsupseteqq", render: "\\nsupseteqq" },
  { icon: "\\subsetneq", render: "\\subsetneq" },
  { icon: "\\supsetneq", render: "\\supsetneq" },
  { icon: "\\subsetneqq", render: "\\subsetneqq" },
  { icon: "\\supsetneqq", render: "\\supsetneqq" },
  { icon: "\\varsubsetneq", render: "\\varsubsetneq" },
  { icon: "\\varsupsetneq", render: "\\varsupsetneq" },
  { icon: "\\varsubsetneqq", render: "\\varsubsetneqq" },
  { icon: "\\varsupsetneqq", render: "\\varsupsetneqq" },
  { icon: "\\land", render: "\\land" },
  { icon: "\\lor", render: "\\lor" },
  { icon: "\\lnot", render: "\\lnot" },
];

export const arrows = [
  { icon: "\\leftarrow", render: "\\leftarrow" },
  { icon: "\\longleftarrow", render: "\\longleftarrow" },
  { icon: "\\Leftarrow", render: "\\Leftarrow" },
  { icon: "\\Longleftarrow", render: "\\Longleftarrow" },
  { icon: "\\rightarrow", render: "\\rightarrow" },
  { icon: "\\longrightarrow", render: "\\longrightarrow" },
  { icon: "\\Rightarrow", render: "\\Rightarrow" },
  { icon: "\\Longrightarrow", render: "\\Longrightarrow" },
  { icon: "\\leftrightarrow", render: "\\leftrightarrow" },
  { icon: "\\longleftrightarrow", render: "\\longleftrightarrow" },
  { icon: "\\Leftrightarrow", render: "\\Leftrightarrow" },
  { icon: "\\Longleftrightarrow", render: "\\Longleftrightarrow" },
  { icon: "\\uparrow", render: "\\uparrow" },
  { icon: "\\Uparrow", render: "\\Uparrow" },
  { icon: "\\downarrow", render: "\\downarrow" },
  { icon: "\\Downarrow", render: "\\Downarrow" },
  { icon: "\\updownarrow", render: "\\updownarrow" },
  { icon: "\\Updownarrow", render: "\\Updownarrow" },
  { icon: "\\nleftarrow", render: "\\nleftarrow" },
  { icon: "\\nrightarrow", render: "\\nrightarrow" },
  { icon: "\\nLeftarrow", render: "\\nLeftarrow" },
  { icon: "\\nRightarrow", render: "\\nRightarrow" },
  { icon: "\\nleftrightarrow", render: "\\nleftrightarrow" },
  { icon: "\\nLeftrightarrow", render: "\\nLeftrightarrow" },
  { icon: "\\to", render: "\\to" },
  { icon: "\\mapsto", render: "\\mapsto" },
  { icon: "\\longmapsto", render: "\\longmapsto" },
  { icon: "\\implies", render: "\\implies" },
  { icon: "\\hookleftarrow", render: "\\hookleftarrow" },
  { icon: "\\hookrightarrow", render: "\\hookrightarrow" },
  { icon: "\\leftharpoonup", render: "\\leftharpoonup" },
  { icon: "\\rightharpoonup", render: "\\rightharpoonup" },
  { icon: "\\leftharpoondown", render: "\\leftharpoondown" },
  { icon: "\\rightharpoondown", render: "\\rightharpoondown" },
  { icon: "\\rightleftharpoons", render: "\\rightleftharpoons" },
  { icon: "\\leftrightharpoons", render: "\\leftrightharpoons" },
  { icon: "\\upharpoonleft", render: "\\upharpoonleft" },
  { icon: "\\downharpoonleft", render: "\\downharpoonleft" },
  { icon: "\\upharpoonright", render: "\\upharpoonright" },
  { icon: "\\downharpoonright", render: "\\downharpoonright" },
  { icon: "\\leadsto", render: "\\leadsto" },
  { icon: "\\nearrow", render: "\\nearrow" },
  { icon: "\\searrow", render: "\\searrow" },
  { icon: "\\swarrow", render: "\\swarrow" },
  { icon: "\\nwarrow", render: "\\nwarrow" },
  { icon: "\\dashrightarrow", render: "\\dashrightarrow" },
  { icon: "\\dashleftarrow", render: "\\dashleftarrow" },
  { icon: "\\leftleftarrows", render: "\\leftleftarrows" },
  { icon: "\\rightrightarrows", render: "\\rightrightarrows" },
  { icon: "\\leftrightarrows", render: "\\leftrightarrows" },
  { icon: "\\rightleftarrows", render: "\\rightleftarrows" },
  { icon: "\\upuparrows", render: "\\upuparrows" },
  { icon: "\\downdownarrows", render: "\\downdownarrows" },
  { icon: "\\twoheadleftarrow", render: "\\twoheadleftarrow" },
  { icon: "\\twoheadrightarrow", render: "\\twoheadrightarrow" },
  { icon: "\\leftarrowtail", render: "\\leftarrowtail" },
  { icon: "\\rightarrowtail", render: "\\rightarrowtail" },
  { icon: "\\rightsquigarrow", render: "\\rightsquigarrow" },
  { icon: "\\leftrightsquigarrow", render: "\\leftrightsquigarrow" },
  { icon: "\\curvearrowleft", render: "\\curvearrowleft" },
  { icon: "\\curvearrowright", render: "\\curvearrowright" },
  { icon: "\\circlearrowleft", render: "\\circlearrowleft" },
  { icon: "\\circlearrowright", render: "\\circlearrowright" },
  { icon: "\\looparrowleft", render: "\\looparrowleft" },
  { icon: "\\looparrowright", render: "\\looparrowright" },
  { icon: "\\Lsh", render: "\\Lsh" },
  { icon: "\\Rsh", render: "\\Rsh" },
  { icon: "\\Lleftarrow", render: "\\Lleftarrow" },
  { icon: "\\Rrightarrow", render: "\\Rrightarrow" },
  { icon: "\\multimap", render: "\\multimap" },
];

export const accents = [
  { icon: "\\hat{a}", render: "\\hat{a}" },
  { icon: "\\dot{a}", render: "\\dot{a}" },
  { icon: "\\check{a}", render: "\\check{a}" },
  { icon: "\\ddot{a}", render: "\\ddot{a}" },
  { icon: "\\tilde{a}", render: "\\tilde{a}" },
  { icon: "\\breve{a}", render: "\\breve{a}" },
  { icon: "\\acute{a}", render: "\\acute{a}" },
  { icon: "\\bar{a}", render: "\\bar{a}" },
  { icon: "\\grave{a}", render: "\\grave{a}" },
  { icon: "\\vec{a}", render: "\\vec{a}" },
];

export const miscellaneous = [
  { icon: "\\infty", render: "\\infty" },
  { icon: "\\nabla", render: "\\nabla" },
  { icon: "\\partial", render: "\\partial" },
  { icon: "\\eth", render: "\\eth" },
  { icon: "\\clubsuit", render: "\\clubsuit" },
  { icon: "\\diamondsuit", render: "\\diamondsuit" },
  { icon: "\\heartsuit", render: "\\heartsuit" },
  { icon: "\\spadesuit", render: "\\spadesuit" },
  { icon: "\\cdots", render: "\\cdots" },
  { icon: "\\vdots", render: "\\vdots" },
  { icon: "\\ldots", render: "\\ldots" },
  { icon: "\\ddots", render: "\\ddots" },
  { icon: "\\Im", render: "\\Im" },
  { icon: "\\Re", render: "\\Re" },
  { icon: "\\forall", render: "\\forall" },
  { icon: "\\exists", render: "\\exists" },
  { icon: "\\nexists", render: "\\nexists" },
  { icon: "\\emptyset", render: "\\emptyset" },
  { icon: "\\varnothing", render: "\\varnothing" },
  { icon: "\\imath", render: "\\imath" },
  { icon: "\\jmath", render: "\\jmath" },
  { icon: "\\ell", render: "\\ell" },
  { icon: "\\sharp", render: "\\sharp" },
  { icon: "\\flat", render: "\\flat" },
  { icon: "\\natural", render: "\\natural" },
  { icon: "\\bigstar", render: "\\bigstar" },
  { icon: "\\diagdown", render: "\\diagdown" },
  { icon: "\\diagup", render: "\\diagup" },
  { icon: "\\Diamond", render: "\\Diamond" },
  { icon: "\\Finv", render: "\\Finv" },
  { icon: "\\Game", render: "\\Game" },
  { icon: "\\hbar", render: "\\hbar" },
  { icon: "\\hslash", render: "\\hslash" },
  { icon: "\\lozenge", render: "\\lozenge" },
  { icon: "\\mho", render: "\\mho" },
  { icon: "\\prime", render: "\\prime" },
  { icon: "\\backprime", render: "\\backprime" },
  { icon: "\\surd", render: "\\surd" },
  { icon: "\\wp", render: "\\wp" },
  { icon: "\\angle", render: "\\angle" },
  { icon: "\\measuredangle", render: "\\measuredangle" },
  { icon: "\\sphericalangle", render: "\\sphericalangle" },
  { icon: "\\complement", render: "\\complement" },
  { icon: "\\triangledown", render: "\\triangledown" },
  { icon: "\\triangle", render: "\\triangle" },
  { icon: "\\vartriangle", render: "\\vartriangle" },
  { icon: "\\blacklozenge", render: "\\blacklozenge" },
  { icon: "\\blacksquare", render: "\\blacksquare" },
  { icon: "\\blacktriangle", render: "\\blacktriangle" },
  { icon: "\\blacktriangledown", render: "\\blacktriangledown" },
  { icon: "\\circledS", render: "\\circledS" },
];

export const letterStyles = [
  { icon: "\\mathcal{A}", render: "\\mathcal{A}" },
  { icon: "\\mathcal{B}", render: "\\mathcal{B}" },
  { icon: "\\mathcal{C}", render: "\\mathcal{C}" },
  { icon: "\\mathcal{D}", render: "\\mathcal{D}" },
  { icon: "\\mathcal{E}", render: "\\mathcal{E}" },
  { icon: "\\mathcal{F}", render: "\\mathcal{F}" },
  { icon: "\\mathcal{G}", render: "\\mathcal{G}" },
  { icon: "\\mathcal{H}", render: "\\mathcal{H}" },
  { icon: "\\mathcal{I}", render: "\\mathcal{I}" },
  { icon: "\\mathcal{J}", render: "\\mathcal{J}" },
  { icon: "\\mathcal{K}", render: "\\mathcal{K}" },
  { icon: "\\mathcal{L}", render: "\\mathcal{L}" },
  { icon: "\\mathcal{M}", render: "\\mathcal{M}" },
  { icon: "\\mathcal{N}", render: "\\mathcal{N}" },
  { icon: "\\mathcal{O}", render: "\\mathcal{O}" },
  { icon: "\\mathcal{P}", render: "\\mathcal{P}" },
  { icon: "\\mathcal{Q}", render: "\\mathcal{Q}" },
  { icon: "\\mathcal{R}", render: "\\mathcal{R}" },
  { icon: "\\mathcal{S}", render: "\\mathcal{S}" },
  { icon: "\\mathcal{T}", render: "\\mathcal{T}" },
  { icon: "\\mathcal{U}", render: "\\mathcal{U}" },
  { icon: "\\mathcal{V}", render: "\\mathcal{V}" },
  { icon: "\\mathcal{W}", render: "\\mathcal{W}" },
  { icon: "\\mathcal{X}", render: "\\mathcal{X}" },
  { icon: "\\mathcal{Y}", render: "\\mathcal{Y}" },
  { icon: "\\mathcal{Z}", render: "\\mathcal{Z}" },
  { icon: "\\mathbb{A}", render: "\\mathbb{A}" },
  { icon: "\\mathbb{B}", render: "\\mathbb{B}" },
  { icon: "\\mathbb{C}", render: "\\mathbb{C}" },
  { icon: "\\mathbb{D}", render: "\\mathbb{D}" },
  { icon: "\\mathbb{E}", render: "\\mathbb{E}" },
  { icon: "\\mathbb{F}", render: "\\mathbb{F}" },
  { icon: "\\mathbb{G}", render: "\\mathbb{G}" },
  { icon: "\\mathbb{H}", render: "\\mathbb{H}" },
  { icon: "\\mathbb{I}", render: "\\mathbb{I}" },
  { icon: "\\mathbb{J}", render: "\\mathbb{J}" },
  { icon: "\\mathbb{K}", render: "\\mathbb{K}" },
  { icon: "\\mathbb{L}", render: "\\mathbb{L}" },
  { icon: "\\mathbb{M}", render: "\\mathbb{M}" },
  { icon: "\\mathbb{N}", render: "\\mathbb{N}" },
  { icon: "\\mathbb{O}", render: "\\mathbb{O}" },
  { icon: "\\mathbb{P}", render: "\\mathbb{P}" },
  { icon: "\\mathbb{Q}", render: "\\mathbb{Q}" },
  { icon: "\\mathbb{R}", render: "\\mathbb{R}" },
  { icon: "\\mathbb{S}", render: "\\mathbb{S}" },
  { icon: "\\mathbb{T}", render: "\\mathbb{T}" },
  { icon: "\\mathbb{U}", render: "\\mathbb{U}" },
  { icon: "\\mathbb{V}", render: "\\mathbb{V}" },
  { icon: "\\mathbb{W}", render: "\\mathbb{W}" },
  { icon: "\\mathbb{X}", render: "\\mathbb{X}" },
  { icon: "\\mathbb{Y}", render: "\\mathbb{Y}" },
  { icon: "\\mathbb{Z}", render: "\\mathbb{Z}" },
  { icon: "\\mathfrak{A}", render: "\\mathfrak{A}" },
  { icon: "\\mathfrak{B}", render: "\\mathfrak{B}" },
  { icon: "\\mathfrak{C}", render: "\\mathfrak{C}" },
  { icon: "\\mathfrak{D}", render: "\\mathfrak{D}" },
  { icon: "\\mathfrak{E}", render: "\\mathfrak{E}" },
  { icon: "\\mathfrak{F}", render: "\\mathfrak{F}" },
  { icon: "\\mathfrak{G}", render: "\\mathfrak{G}" },
  { icon: "\\mathfrak{H}", render: "\\mathfrak{H}" },
  { icon: "\\mathfrak{I}", render: "\\mathfrak{I}" },
  { icon: "\\mathfrak{J}", render: "\\mathfrak{J}" },
  { icon: "\\mathfrak{K}", render: "\\mathfrak{K}" },
  { icon: "\\mathfrak{L}", render: "\\mathfrak{L}" },
  { icon: "\\mathfrak{M}", render: "\\mathfrak{M}" },
  { icon: "\\mathfrak{N}", render: "\\mathfrak{N}" },
  { icon: "\\mathfrak{O}", render: "\\mathfrak{O}" },
  { icon: "\\mathfrak{P}", render: "\\mathfrak{P}" },
  { icon: "\\mathfrak{Q}", render: "\\mathfrak{Q}" },
  { icon: "\\mathfrak{R}", render: "\\mathfrak{R}" },
  { icon: "\\mathfrak{S}", render: "\\mathfrak{S}" },
  { icon: "\\mathfrak{T}", render: "\\mathfrak{T}" },
  { icon: "\\mathfrak{U}", render: "\\mathfrak{U}" },
  { icon: "\\mathfrak{V}", render: "\\mathfrak{V}" },
  { icon: "\\mathfrak{W}", render: "\\mathfrak{W}" },
  { icon: "\\mathfrak{X}", render: "\\mathfrak{X}" },
  { icon: "\\mathfrak{Y}", render: "\\mathfrak{Y}" },
  { icon: "\\mathfrak{Z}", render: "\\mathfrak{Z}" },
  { icon: "\\mathsf{A}", render: "\\mathsf{A}" },
  { icon: "\\mathsf{B}", render: "\\mathsf{B}" },
  { icon: "\\mathsf{C}", render: "\\mathsf{C}" },
  { icon: "\\mathsf{D}", render: "\\mathsf{D}" },
  { icon: "\\mathsf{E}", render: "\\mathsf{E}" },
  { icon: "\\mathsf{F}", render: "\\mathsf{F}" },
  { icon: "\\mathsf{G}", render: "\\mathsf{G}" },
  { icon: "\\mathsf{H}", render: "\\mathsf{H}" },
  { icon: "\\mathsf{I}", render: "\\mathsf{I}" },
  { icon: "\\mathsf{J}", render: "\\mathsf{J}" },
  { icon: "\\mathsf{K}", render: "\\mathsf{K}" },
  { icon: "\\mathsf{L}", render: "\\mathsf{L}" },
  { icon: "\\mathsf{M}", render: "\\mathsf{M}" },
  { icon: "\\mathsf{N}", render: "\\mathsf{N}" },
  { icon: "\\mathsf{O}", render: "\\mathsf{O}" },
  { icon: "\\mathsf{P}", render: "\\mathsf{P}" },
  { icon: "\\mathsf{Q}", render: "\\mathsf{Q}" },
  { icon: "\\mathsf{R}", render: "\\mathsf{R}" },
  { icon: "\\mathsf{S}", render: "\\mathsf{S}" },
  { icon: "\\mathsf{T}", render: "\\mathsf{T}" },
  { icon: "\\mathsf{U}", render: "\\mathsf{U}" },
  { icon: "\\mathsf{V}", render: "\\mathsf{V}" },
  { icon: "\\mathsf{W}", render: "\\mathsf{W}" },
  { icon: "\\mathsf{X}", render: "\\mathsf{X}" },
  { icon: "\\mathsf{Y}", render: "\\mathsf{Y}" },
  { icon: "\\mathsf{Z}", render: "\\mathsf{Z}" },
  { icon: "\\mathbf{A}", render: "\\mathbf{A}" },
  { icon: "\\mathbf{B}", render: "\\mathbf{B}" },
  { icon: "\\mathbf{C}", render: "\\mathbf{C}" },
  { icon: "\\mathbf{D}", render: "\\mathbf{D}" },
  { icon: "\\mathbf{E}", render: "\\mathbf{E}" },
  { icon: "\\mathbf{F}", render: "\\mathbf{F}" },
  { icon: "\\mathbf{G}", render: "\\mathbf{G}" },
  { icon: "\\mathbf{H}", render: "\\mathbf{H}" },
  { icon: "\\mathbf{I}", render: "\\mathbf{I}" },
  { icon: "\\mathbf{J}", render: "\\mathbf{J}" },
  { icon: "\\mathbf{K}", render: "\\mathbf{K}" },
  { icon: "\\mathbf{L}", render: "\\mathbf{L}" },
  { icon: "\\mathbf{M}", render: "\\mathbf{M}" },
  { icon: "\\mathbf{N}", render: "\\mathbf{N}" },
  { icon: "\\mathbf{O}", render: "\\mathbf{O}" },
  { icon: "\\mathbf{P}", render: "\\mathbf{P}" },
  { icon: "\\mathbf{Q}", render: "\\mathbf{Q}" },
  { icon: "\\mathbf{R}", render: "\\mathbf{R}" },
  { icon: "\\mathbf{S}", render: "\\mathbf{S}" },
  { icon: "\\mathbf{T}", render: "\\mathbf{T}" },
  { icon: "\\mathbf{U}", render: "\\mathbf{U}" },
  { icon: "\\mathbf{V}", render: "\\mathbf{V}" },
  { icon: "\\mathbf{W}", render: "\\mathbf{W}" },
  { icon: "\\mathbf{X}", render: "\\mathbf{X}" },
  { icon: "\\mathbf{Y}", render: "\\mathbf{Y}" },
  { icon: "\\mathbf{Z}", render: "\\mathbf{Z}" },
];

export const symbols = [
  ...greekAndHebrewLetters.map((s) => ({
    ...s,
    category: "greek and hebrew letters",
  })),
  ...delimiters.map((s) => ({
    ...s,
    category: "delimiters",
  })),
  ...mathsConstructs.map((s) => ({
    ...s,
    category: "maths constructs",
  })),
  ...variableSizedSymbols.map((s) => ({
    ...s,
    category: "variable sized symbols",
  })),
  ...standardFunctions.map((s) => ({
    ...s,
    category: "standard functions",
  })),
  ...operatorsAndRelations.map((s) => ({
    ...s,
    category: "operators and relations",
  })),
  ...arrows.map((s) => ({
    ...s,
    category: "arrows",
  })),
  ...accents.map((s) => ({
    ...s,
    category: "accents",
  })),
  ...miscellaneous.map((s) => ({
    ...s,
    category: "miscellaneous",
  })),
  ...letterStyles.map((s) => ({
    ...s,
    category: "letter styles",
  })),
].map((s) => ({
  ...s,
  html: katex.renderToString(s.render),
}));
